language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py -c travis.cfg --buildout-version 2.7.0 --setuptools-version 36.8.0
  - bin/buildout -Nc travis.cfg
script:
    - bin/test --all
